services:
  api:
    build:
      context: .
      dockerfile: ./Docker/Dockerfile.dev
    image: algafood-api
    ports:
      - '${FOWARD_APP_PORT:-8080}:8080'
      - '${FOWARD_DEBUG_PORT:-8081}:8081'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - '.:/app'
    networks:
      - algafood
  mysql:
    image: 'mysql/mysql-server:8.0'
    ports:
      - '${FOWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - 'algaworks-mysql:/var/lib/mysql'
    networks:
      - algafood
networks:
  algafood:
    driver: bridge
volumes:
  algaworks-mysql:
    driver: local
